/* Algorithm explanation page. Numbers are read live from /api/config so the page cannot drift from the code. */
function pgAlgorithm(cfg) {
  var c = cfg.config, wn = c.weights_normal, we = c.weights_emergency, J = c.J;
  var W = function (w) { return 'w_u=' + w.u + '  w_w=' + w.w + '  w_d=' + w.d + '  w_r=' + w.r + '  w_c=' + w.c; };
  var E = function (t) { return '<div class="eq">' + esc(t) + '</div>'; };
  var strat = Object.keys(cfg.strategies).map(function (k) { var s = cfg.strategies[k]; return '<tr><td>' + esc(s.label) + '</td><td>' + (s.lookahead ? 'yes' : 'no') + '</td><td>' + (s.cost_aware ? 'yes' : 'no') + '</td><td>' + (s.local_search ? 'yes' : 'no') + '</td><td>' + (s.adaptive_emergency ? 'yes' : 'no') + '</td><td class="mono small">' + esc(s.weights ? JSON.stringify(s.weights) : 'config weights') + '</td></tr>'; });
  var ind = Object.keys(c.emergency).map(function (k) { var i = c.emergency[k]; return '<tr><td>' + esc(i.label) + '</td><td>' + (i.low ? '&le;' : '&ge;') + i.warn + '</td><td>' + (i.low ? '&le;' : '&ge;') + i.emergency + '</td></tr>'; });
  return '<div class="page algo"><h2>How MedFlow decides</h2><p class="muted">Operations decision-support prototype. Parameters below are prototype settings, not clinically validated. Values shown are the live configuration.</p>' +
    '<h3>1. Patient priority score</h3><p>Each waiting patient p gets a score from five components, each normalised to [0,1]:</p>' +
    E('S_p = w_u*U_p + w_w*W_p + w_d*D_p + w_r*R_p + w_c*C_p\n\nU_p = (urgency - 1) / 9                       urgency 1..10\nW_p = min(1, wait_p / target[category])       waiting pressure\nD_p = 1 - (1 - r0) * exp(-h[category] * wait_p),  r0 = ' + c.baseline_risk_factor + ' * C_p   deterioration\nR_p = (# required resource classes free now) / (# required classes)\nC_p = expert-system risk score (+0.05 per observed deterioration)') +
    '<p>NORMAL weights: <span class="mono">' + W(wn) + '</span><br>EMERGENCY weights: <span class="mono">' + W(we) + '</span><br>Targets (min): <span class="mono">' + esc(JSON.stringify(c.target_wait)) + '</span> - hazards per waiting minute: <span class="mono">' + esc(JSON.stringify(c.hazard_per_min)) + '</span></p>' +
    '<p><b>Normalisation:</b> waiting pressure is measured against the category\'s own target, so a LOW patient that has waited 90 min ages to the same pressure as a CRITICAL patient at 5 min. This prevents starvation without letting waiting alone outrank urgency.</p>' +
    '<h3>2. Hard constraints (never traded against the objective)</h3>' + E('H1 capacity / no double booking:  sum_p x(p,r,t) <= 1 for every bed, doctor, nurse, equipment unit r at every time t\nH2 bed compatibility:   ICU-level -> ICU bed only; theatre -> theatre; ER critical -> emergency bed; overflow only to permitted types\nH3 skill:               doctor holds required specialty\nH4 nurse skill + zone:  nurse holds ALL required skills and covers the bed\'s ward (department constraint)\nH5 availability:        on shift, not unavailable, not off-shift; failed/cleaning resources excluded\nH6 equipment:           required units free') +
    '<p>If no bundle satisfies H1-H6 within the horizon, the patient is reported as <i>unscheduled</i> with the exact conflict (e.g. "ICU capacity constrained: 2 waiting patient(s) require a compatible bed but only 1 of 5 operational compatible bed(s) are free"). Nothing is silently assigned.</p>' +
    '<h3>3. Objective</h3>' + E('J = alpha*sum(wait) + beta*sum m_p*(wait_p/target_p)^2 + gamma*idle + delta*travel + epsilon*unserved + zeta*reassign\n\nalpha=' + J.alpha + ' beta=' + J.beta + ' gamma=' + J.gamma + ' delta=' + J.delta + ' epsilon=' + J.epsilon + ' zeta=' + J.zeta + '   (m_p = ' + esc(JSON.stringify(c.critical_multiplier)) + ' for HIGH / CRITICAL; beta x' + c.emergency_beta_mult + ' in Emergency Mode)') +
    '<p>The squared, target-relative critical term is what stops a schedule with a small average wait from hiding one critical patient waiting far too long: doubling a critical patient\'s wait quadruples its penalty.</p>' +
    '<h3>4. How the schedule is built (priority-ordered serial scheduling with backfilling)</h3><p>Patients are visited in descending S_p. Each takes the <b>earliest start time</b> at which a feasible bundle (bed, doctor, k nurses, equipment) exists on the resource calendars, and books it. Lower-priority patients can only use gaps that do not delay a higher-priority reservation. Among feasible bundles the cheapest is chosen:</p>' +
    E('cost = (alpha+delta)*travel_minutes + workload_weight*utilisation_so_far + scarcity_weight*sum(1/#staff holding an unneeded skill)\n       + bed_class_penalty + ward_mismatch + continuity_with_previous_plan') +
    '<p>Then a local search swaps adjacent patients in the priority order and keeps a swap only if the full plan\'s J decreases (' + c.ls_iters + ' passes, window ' + c.ls_window + '). This is a constructive heuristic plus local search - it is not a proven-optimal MILP. Complexity per epoch is O(P * T * (B*(D+N))) for P waiting patients, T candidate start times, B beds, D doctors, N nurses; local search multiplies it by at most ' + (c.ls_iters * c.ls_window) + '.</p>' +
    '<h3>5. Rolling-horizon re-optimization</h3>' + E('observe state(t) -> plan (horizon ' + c.horizon + ' min) -> commit only assignments due NOW -> advance time -> observe events -> re-plan') +
    '<p>Re-optimization is triggered by arrivals, completions, treatment overruns, deterioration, shift changes, resource failures/changes and mode changes, and at least every ' + c.replan_interval + ' min. Only the current step is committed; everything else stays tentative, which is why the "next task" shown to nurses and doctors can change. The previous plan is used as a continuity term so the smallest necessary change is preferred.</p>' +
    '<h3>6. Uncertain treatment duration</h3>' + E('actual = nominal * bias[dept] * exp(sigma*Z - sigma^2/2),   Z ~ N(0,1),   sigma = ' + c.duration_sigma + '   (mean-preserving log-normal)\nwhile elapsed >= predicted end:  predicted end += max(' + c.overrun_extension_min + ', ' + c.overrun_extension_frac + ' * expected)') +
    '<p>The optimizer never sees the actual duration. When a treatment passes its predicted end the resource stays occupied, the deviation is logged, the estimate is extended, and downstream assignments are re-planned. An optional online predictor learns a per-department bias (EWMA, rate ' + c.adaptive_lr + ') and its accuracy is reported.</p>' +
    '<h3>7. Bottleneck detection</h3>' + E('U_r = busy/capacity     DP_r = min(3, (busy + queued)/capacity)     QG_r = 1 + max(0, queue growth over ' + c.growth_window + ' min)/capacity\nB_r = U_r * DP_r * QG_r         bottleneck if B_r >= ' + c.bottleneck_threshold + ' and patients are blocked on r') +
    '<p>"Blocked on r" is attributed by the planner: the resource role that becomes available last for a patient is that patient\'s binding constraint. Recommendations (move a nurse, call in on-call staff, open a temporary bed, add equipment) are evaluated <b>counterfactually</b> by re-running the planner on a copy of the hospital with the change applied; the projected wait change is the difference between the two plans.</p>' +
    '<h3>8. Automatic Emergency Mode</h3><p>NORMAL &rarr; WARNING &rarr; EMERGENCY &rarr; RECOVERY &rarr; NORMAL, driven by measurable indicators (configurable, not medically validated). Escalation needs ' + c.em_confirm_min + ' consecutive minutes; leaving Emergency needs all indicators below ' + c.em_exit_factor + 'x their thresholds for ' + c.em_recovery_min + ' min (hysteresis). In Emergency Mode the planner switches to emergency weights, weights critical lateness more, stops low-urgency patients from occupying higher-level beds, and auto-applies the best counterfactual intervention (cooldown ' + c.auto_cooldown + ' min).</p>' +
    table(['Indicator', 'Warning', 'Emergency'], ind) +
    '<h3>9. Strategies compared</h3>' + table(['Strategy', 'Look-ahead reservations', 'Cost-aware bundles', 'Local search', 'Emergency adaptation', 'Priority weights'], strat) +
    '<h3>10. Prediction layer and decision support</h3><p>Optimizer &larr; PredictionService &larr; {duration, demand, risk, resource-demand predictors}. Predictions are inputs only: even a perfect prediction cannot make the optimizer break H1-H6. The triage expert system is rule-based decision support (noisy-OR over symptom and vital-sign weights); it is not a diagnosis.</p>' +
    '<h3>11. Limitations</h3><ul><li>Heuristic optimizer, no optimality proof.</li><li>Single task per staff member (a nurse handles one patient at a time); treatments are non-preemptive.</li><li>Weights, targets and thresholds are operational parameters, not clinical standards.</li><li>Synthetic patient stream unless a dataset is ingested; operational fields are always simulated.</li><li>Prototype authentication only.</li></ul></div>';
}
